/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manageBorrows;

import manageBooks.*;
import manageUser.*;
import auth.*;
import auth.*;
import javax.swing.JOptionPane;

public class addBorrow extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public addBorrow() {
        initComponents();
        loadUsers();
        loadBooks();
        setBorrowDateNow();
    }

    private void loadUsers() {
        try {
            config.dbConnect db = new config.dbConnect();
            String query = "SELECT UserID, Username FROM user";
            java.sql.ResultSet rs = db.getData(query);
            selectuser.removeAllItems();
            selectuser.addItem("Select User");
            while (rs.next()) {
                int userId = rs.getInt("UserID");
                String username = rs.getString("Username");
                selectuser.addItem(userId + " - " + username);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to load users: " + e.getMessage());
        }
    }

    private void loadBooks() {
        try {
            config.dbConnect db = new config.dbConnect();
            String query = "SELECT BookID, Title FROM book";
            java.sql.ResultSet rs = db.getData(query);
            selectbook.removeAllItems();
            selectbook.addItem("Select Book");
            while (rs.next()) {
                int bookId = rs.getInt("BookID");
                String title = rs.getString("Title");
                selectbook.addItem(bookId + " - " + title);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to load books: " + e.getMessage());
        }
    }

    private void setBorrowDateNow() {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String now = sdf.format(new java.util.Date());
        borrowdate.setText(now);
    }

    private void borrowbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowbookActionPerformed
        try {
            if (selectuser.getSelectedIndex() <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a user.");
                return;
            }
            if (selectbook.getSelectedIndex() <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a book.");
                return;
            }
            String returnDate = returndate.getText().trim();
            if (returnDate.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter a return date.");
                return;
            }

            int userId = Integer.parseInt(selectuser.getSelectedItem().toString().split(" - ")[0]);
            int bookId = Integer.parseInt(selectbook.getSelectedItem().toString().split(" - ")[0]);
            String borrowDate = borrowdate.getText().trim();

            config.dbConnect db = new config.dbConnect();

            // Insert borrow record with status 'Pending'
            String insertSql = "INSERT INTO borrows (UserID, BookID, BorrowDate, ReturnDate, Status) VALUES ("
                    + userId + ", " + bookId + ", '" + borrowDate + "', '" + returnDate + "', 'Pending')";
            int result = db.InsertData(insertSql);
            if (result == 1) {
                // Decrease copies available in book table by 1
                String updateBookSql = "UPDATE book SET CopiesAvailable = CopiesAvailable - 1 WHERE BookID = " + bookId;
                db.InsertData(updateBookSql);

                javax.swing.JOptionPane.showMessageDialog(this, "Book borrowed successfully!");
                new manageBorrows().setVisible(true);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to borrow book. Please try again.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_borrowbookActionPerformed

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        borrowdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        returndate = new javax.swing.JTextField();
        borrowbook = new javax.swing.JButton();
        selectuser = new javax.swing.JComboBox<>();
        selectbook = new javax.swing.JComboBox<>();
        Background = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Borrow a Book");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 50));

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backicon.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        jPanel2.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 80, 20));

        borrowdate.setBackground(new java.awt.Color(255, 255, 255));
        borrowdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        borrowdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        borrowdate.setEnabled(false);
        jPanel2.add(borrowdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 280, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Borrow Date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 130, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Return Date");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 120, 20));

        returndate.setBackground(new java.awt.Color(255, 255, 255));
        returndate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        returndate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(returndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 280, 30));

        borrowbook.setBackground(new java.awt.Color(255, 255, 255));
        borrowbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrowbook.setForeground(new java.awt.Color(0, 0, 0));
        borrowbook.setText("Borrow");
        borrowbook.setBorder(null);
        borrowbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowbookActionPerformed(evt);
            }
        });
        jPanel2.add(borrowbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 170, 30));

        selectuser.setBackground(new java.awt.Color(255, 255, 255));
        selectuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User" }));
        selectuser.setBorder(null);
        jPanel2.add(selectuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 280, 30));

        selectbook.setBackground(new java.awt.Color(255, 255, 255));
        selectbook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Book" }));
        selectbook.setBorder(null);
        jPanel2.add(selectbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 280, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 580, 430));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        new manageBorrows().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonMouseClicked

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addBorrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addBorrow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel backbutton;
    private javax.swing.JButton borrowbook;
    private javax.swing.JTextField borrowdate;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField returndate;
    private javax.swing.JComboBox<String> selectbook;
    private javax.swing.JComboBox<String> selectuser;
    // End of variables declaration//GEN-END:variables
}
