/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import auth.*;
import auth.*;
import javax.swing.JOptionPane;
import utils.receipt;

public class myborrowed extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public myborrowed() {
        initComponents();
        loadBorrowedBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        backbutton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        borrowedbooks = new javax.swing.JTable();
        viewborrow = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a.setText("My Borrowed Books");
        jPanel2.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 500, 50));

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backicon.png"))); // NOI18N
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        jPanel2.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 60));

        borrowedbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(borrowedbooks);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 750, -1));

        viewborrow.setBackground(new java.awt.Color(255, 255, 255));
        viewborrow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewborrow.setForeground(new java.awt.Color(0, 0, 0));
        viewborrow.setText("View Borrowed");
        viewborrow.setBorder(null);
        viewborrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewborrowActionPerformed(evt);
            }
        });
        jPanel2.add(viewborrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 830, 560));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        new userdashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbuttonMouseClicked

    private void viewborrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewborrowActionPerformed
        try {
            int selectedRow = borrowedbooks.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please select a borrowed book to view its receipt.");
                return;
            }
            int borrowId = Integer.parseInt(borrowedbooks.getValueAt(selectedRow, 0).toString());
            new utils.myborrowedreceipt(borrowId).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error opening receipt: " + e.getMessage());
        }
    }//GEN-LAST:event_viewborrowActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadBorrowedBooks();
    }//GEN-LAST:event_formWindowOpened

    private void loadBorrowedBooks() {
        try {
            config.usersession session = config.usersession.getInstance();
            int userId = session.getId();
            System.out.println("Loading borrowed books for userId: " + userId);
            config.dbConnect db = new config.dbConnect();
            String query = "SELECT b.BorrowID, bk.Title AS BookTitle, b.BorrowDate, b.ReturnDate,b.Status FROM borrow b JOIN book bk ON b.BookID = bk.BookID WHERE b.UserID = " + userId;
            java.sql.ResultSet rs = db.getData(query);

            // Set table model
            String[] columnNames = {"Borrow ID", "Book Title", "Borrow Date", "Return Date", "Status"};
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);

            int rowCount = 0;
            while (rs.next()) {
                int borrowId = rs.getInt("BorrowID");
                String bookTitle = rs.getString("BookTitle");
                String borrowDate = rs.getString("BorrowDate");
                String returnDate = rs.getString("ReturnDate");
                String status = rs.getString("Status");
                Object[] row = {borrowId, bookTitle, borrowDate, returnDate, status};
                model.addRow(row);
                rowCount++;
            }
            System.out.println("Number of borrowed books loaded: " + rowCount);
            borrowedbooks.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading borrowed books: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myborrowed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myborrowed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myborrowed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myborrowed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myborrowed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel a;
    private javax.swing.JLabel backbutton;
    private javax.swing.JTable borrowedbooks;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewborrow;
    // End of variables declaration//GEN-END:variables
}
