/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;

import auth.*;
import auth.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class myborrowedreceipt extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public myborrowedreceipt() {
        initComponents();
    }

    public myborrowedreceipt(int borrowId) {
        initComponents();
        loadReceiptDetails(borrowId);
    }

    private void loadReceiptDetails(int borrowId) {
        try {
            config.dbConnect db = new config.dbConnect();
            String query = "SELECT CONCAT(u.FirstName, ' ', u.LastName) as borrowerName, u.Email as email, u.Phone as phone, u.Address as address, " +
                           "b.Title as bookTitle, b.Author as author, b.ISBN as isbn, br.BorrowDate as borrowDate, br.ReturnDate as returnDate, br.Status as status " +
                           "FROM borrow br " +
                           "JOIN user u ON br.UserID = u.UserID " +
                           "JOIN book b ON br.BookID = b.BookID " +
                           "WHERE br.BorrowID = " + borrowId;
            java.sql.ResultSet rs = db.getData(query);
            if (rs.next()) {
                setReceiptDetails(
                    rs.getString("borrowerName"),
                    rs.getString("email"),
                    rs.getString("phone"),
                    rs.getString("address"),
                    rs.getString("bookTitle"),
                    rs.getString("author"),
                    rs.getString("isbn"),
                    rs.getString("borrowDate"),
                    rs.getString("returnDate"),
                    rs.getString("status")
                );
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Receipt details not found for Borrow ID: " + borrowId);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading receipt details: " + e.getMessage());
        }
    }

    public void setReceiptDetails(String borrowerName, String email, String phone, String address, String bookTitle, String author, String isbn, String borrowDate, String returnDate, String status) {
        this.borrowername.setText(borrowerName);
        this.email.setText(email);
        this.phone.setText(phone);
        this.address.setText(address);
        this.booktitle.setText(bookTitle);
        this.author.setText(author);
        this.isbn.setText(isbn);
        this.borrowdate.setText(borrowDate);
        this.returndate.setText(returnDate);
        this.status.setText(status);
    }

    public void setReceiptFromModel(utils.BorrowRecord record) {
        this.borrowername.setText(record.getBorrowerName());
        this.email.setText(record.getEmail());
        this.phone.setText(record.getPhone());
        this.address.setText(record.getAddress());
        this.booktitle.setText(record.getBookTitle());
        this.author.setText(record.getAuthor());
        this.isbn.setText(record.getIsbn());
        this.borrowdate.setText(record.getBorrowDate());
        this.returndate.setText(record.getReturnDate());
        this.status.setText(record.getStatus());
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        borrowername = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        receiptId = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        booktitle = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        borrowdate = new javax.swing.JLabel();
        returndate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        borrowername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        borrowername.setForeground(new java.awt.Color(0, 0, 0));
        borrowername.setText("1");
        getContentPane().add(borrowername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 310, 30));

        status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        status.setForeground(new java.awt.Color(0, 0, 0));
        status.setText("1\\");
            getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 310, 30));

            receiptId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            receiptId.setForeground(new java.awt.Color(0, 0, 0));
            receiptId.setText("1\\");
                getContentPane().add(receiptId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 310, 30));

                email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                email.setForeground(new java.awt.Color(0, 0, 0));
                email.setText("1\\");
                    getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 310, 40));

                    phone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                    phone.setForeground(new java.awt.Color(0, 0, 0));
                    phone.setText("1\\");
                        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 310, 30));

                        address.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                        address.setForeground(new java.awt.Color(0, 0, 0));
                        address.setText("1\\");
                            getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 310, 30));

                            booktitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                            booktitle.setForeground(new java.awt.Color(0, 0, 0));
                            booktitle.setText("1\\");
                                getContentPane().add(booktitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 310, 40));

                                author.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                                author.setForeground(new java.awt.Color(0, 0, 0));
                                author.setText("1\\");
                                    getContentPane().add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 310, 30));

                                    isbn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                                    isbn.setForeground(new java.awt.Color(0, 0, 0));
                                    isbn.setText("1\\");
                                        getContentPane().add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 310, 30));

                                        borrowdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                                        borrowdate.setForeground(new java.awt.Color(0, 0, 0));
                                        borrowdate.setText("1\\");
                                            getContentPane().add(borrowdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 310, 40));

                                            returndate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                                            returndate.setForeground(new java.awt.Color(0, 0, 0));
                                            returndate.setText("1\\");
                                                getContentPane().add(returndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 310, 30));

                                                jLabel1.setForeground(new java.awt.Color(0, 0, 0));
                                                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receipt.jpg"))); // NOI18N

        // Removed org.jdesktop.beansbinding.BindingGroup and related binding code to fix casting error

        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myborrowedreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myborrowedreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myborrowedreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myborrowedreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myborrowedreceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel author;
    private javax.swing.JLabel booktitle;
    private javax.swing.JLabel borrowdate;
    private javax.swing.JLabel borrowername;
    private javax.swing.JLabel email;
    private javax.swing.JLabel isbn;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel receiptId;
    private javax.swing.JLabel returndate;
    private javax.swing.JLabel status;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
