/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auth;

import javax.swing.JOptionPane;

public class forgotpassword extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public forgotpassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        signin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        secretanswer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        checkbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 390, 50));

        signin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin.setText("Back to Log in");
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        jPanel2.add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 170, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 110, 20));

        registerbutton.setBackground(new java.awt.Color(255, 255, 255));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(0, 0, 0));
        registerbutton.setText("Change");
        registerbutton.setBorder(null);
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 170, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Username");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, 20));

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 280, 30));

        secretanswer.setBackground(new java.awt.Color(255, 255, 255));
        secretanswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secretanswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(secretanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("What is your mother’s maiden name?");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 280, 20));

        passwordfield.setBackground(new java.awt.Color(255, 255, 255));
        passwordfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passwordfield.setEnabled(false);
        jPanel2.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 280, 30));

        confirmpassword.setBackground(new java.awt.Color(255, 255, 255));
        confirmpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        confirmpassword.setEnabled(false);
        jPanel2.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 280, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Confirm Password");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 20));

        checkbutton.setBackground(new java.awt.Color(255, 255, 255));
        checkbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkbutton.setForeground(new java.awt.Color(0, 0, 0));
        checkbutton.setText("Check");
        checkbutton.setBorder(null);
        checkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(checkbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 390, 460));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // Change password action
        String user = username.getText().trim();
        char[] passChars = passwordfield.getPassword();
        String newPass = new String(passChars);
        char[] confirmPassChars = confirmpassword.getPassword();
        String confirmPass = new String(confirmPassChars);

        if (newPass.isEmpty() || confirmPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter and confirm your new password.");
            return;
        }

        if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return;
        }

        if (newPass.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long.");
            return;
        }

        try {
            String hashedPass = config.dbConnect.hashPassword(newPass);
            config.dbConnect db = new config.dbConnect();
            String updateSql = "UPDATE users SET Password = '" + hashedPass + "' WHERE Username = '" + user + "'";
            int result = db.InsertData(updateSql);
            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Password changed successfully!");
                // Optionally disable password fields again
                passwordfield.setEnabled(false);
                confirmpassword.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to change password. Please try again.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
       new login().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_signinMouseClicked

    private void checkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbuttonActionPerformed
        // Check username and secret answer
        String user = username.getText().trim();
        String secretAns = secretanswer.getText().trim();

        if (user.isEmpty() || secretAns.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and secret answer.");
            return;
        }

        try {
            config.dbConnect db = new config.dbConnect();
            String query = "SELECT * FROM users WHERE Username = '" + user + "' AND secretanswer = '" + secretAns + "'";
            java.sql.ResultSet rs = db.getData(query);
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Verification successful! You can now change your password.");
                passwordfield.setEnabled(true);
                confirmpassword.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or secret answer.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_checkbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkbutton;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JButton registerbutton;
    private javax.swing.JTextField secretanswer;
    private javax.swing.JLabel signin;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
