/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auth;

import javax.swing.JOptionPane;

public class register extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        firstname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JTextField();
        signin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        secretanswer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstname.setBackground(new java.awt.Color(255, 255, 255));
        firstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign up");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 50));

        passwordfield.setBackground(new java.awt.Color(255, 255, 255));
        passwordfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 280, 30));

        signin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin.setText("or Sign in");
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        jPanel2.add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 170, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 110, 20));

        registerbutton.setBackground(new java.awt.Color(255, 255, 255));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(0, 0, 0));
        registerbutton.setText("Register");
        registerbutton.setBorder(null);
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 170, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("First Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 20));

        lastname.setBackground(new java.awt.Color(255, 255, 255));
        lastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Last Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 80, 20));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 280, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Email");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, 20));

        phonenumber.setBackground(new java.awt.Color(255, 255, 255));
        phonenumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 280, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Phone Number");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 120, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Address");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 20));

        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 280, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Username");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 120, 20));

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 280, 30));

        secretanswer.setBackground(new java.awt.Color(255, 255, 255));
        secretanswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(secretanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 280, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("What is your mother’s maiden name?");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 280, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 390, 540));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // Handle user registration
        String fname = firstname.getText().trim();
        String lname = lastname.getText().trim();
        String user = username.getText().trim();
        String pass = passwordfield.getText();
        String mail = email.getText().trim();
        String phone = phonenumber.getText().trim();
        String addr = address.getText().trim();
        String secretAns = secretanswer.getText().trim();

        // Validate required fields
        if (fname.isEmpty() || lname.isEmpty() || user.isEmpty() || pass.isEmpty() || mail.isEmpty() || secretAns.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all required fields (First Name, Last Name, Username, Password, Email, Secret Answer).");
            return;
        }

        // Validate password length
        if (pass.length() < 8) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long.");
            return;
        }

        // Validate phone number contains only digits (if not empty)
        if (!phone.isEmpty() && !phone.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Phone number should contain only digits.");
            return;
        }

        try {
            // Hash the password
            String hashedPass = config.dbConnect.hashPassword(pass);

            // Check if username or email already exists
            config.dbConnect db = new config.dbConnect();
            String checkUserSql = "SELECT * FROM users WHERE username = '" + user + "' OR email = '" + mail + "'";
            java.sql.ResultSet rs = db.getData(checkUserSql);
            if (rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Username or Email already exists. Please choose another.");
                return;
            }

            // Insert new user including secret answer
            String insertSql = "INSERT INTO users (FirstName, LastName, Username, Password, Email, Phone, Address, Status, Role, image, secretanswer) VALUES ('"
                    + fname + "', '" + lname + "', '" + user + "', '" + hashedPass + "', '" + mail + "', '" + phone + "', '" + addr + "', 'Pending', 'User', 'src/images/Background.png', '" + secretAns + "')";
            int result = db.InsertData(insertSql);
            if (result == 1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Registration successful!");
              
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Registration failed. Please try again.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
       new login().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_signinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JButton registerbutton;
    private javax.swing.JTextField secretanswer;
    private javax.swing.JLabel signin;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
